### ISSUE TITLE
Filtrar convidados de outro subevento não funciona

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#781]
- [ ] Quando seleciona a lista não muda.
- [ ] Colocar a quantidade de convidados filtrados, esta informação já vem na resposta da API.

**Comment by antonioribeiro** [comment]
```
[2019-03-07 10:33:21] production.ERROR: Trying to get property 'photo' of non-object {"userId":26,"email":"gsbarbosa@alerj.rj.gov.br","exception":"[object] (ErrorException(code: 0): Trying to get property 'photo' of non-object at /home/forge/alerj.3ventz.com/app/Data/Repositories/People.php:32)
[stacktrace]
#0 /home/forge/alerj.3ventz.com/app/Data/Repositories/People.php(32): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/home/forge/ale...', 32, Array)
#1 /home/forge/alerj.3ventz.com/app/Http/Controllers/Api/People.php(50): App\\Data\\Repositories\\People->getPhotoResponse('3315')
#2 [internal function]: App\\Http\\Controllers\\Api\\People->photo('3315')
#3 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('photo', Array)
#5 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\People), 'photo')
#6 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#8 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /home/forge/alerj.3ventz.com/app/Http/Middleware/MustBeAppUser.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\MustBeAppUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
```

**Comment by antonioribeiro** [comment]
Outro erro

```
==> storage/logs/laravel.log <==
[2019-03-07 10:58:11] production.ERROR: Trying to get property 'client_id' of non-object {"userId":1,"email":"afaria@alerj.rj.gov.br","exception":"[object] (ErrorException(code: 0): Trying to get property 'client_id' of non-object at /home/forge/alerj.3ventz.com/app/Data/Models/Invitation.php:389)
[stacktrace]
#0 /home/forge/alerj.3ventz.com/app/Data/Models/Invitation.php(389): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/home/forge/ale...', 389, Array)
#1 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(444): App\\Data\\Models\\Invitation->getClientIdAttribute(2)
#2 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(344): Illuminate\\Database\\Eloquent\\Model->mutateAttribute('client_id', 2)
#3 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(317): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('client_id')
#4 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1515): Illuminate\\Database\\Eloquent\\Model->getAttribute('client_id')
#5 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php(134): Illuminate\\Database\\Eloquent\\Model->__get('client_id')
#6 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php(117): Illuminate\\Database\\Eloquent\\Relations\\BelongsTo->getEagerModelKeys(Array)
#7 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(558): Illuminate\\Database\\Eloquent\\Relations\\BelongsTo->addEagerConstraints(Array)
#8 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(536): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'client', Object(Closure))
#9 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(504): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#10 /home/forge/alerj.3ventz.com/app/Data/Repositories/Invitables.php(29): Illuminate\\Database\\Eloquent\\Builder->get()
#11 [internal function]: App\\Data\\Repositories\\Invitables->App\\Data\\Repositories\\{closure}(Object(App\\Data\\Models\\PersonInstitution), 33)
#12 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1034): array_map(Object(Closure), Array, Array)
#13 /home/forge/alerj.3ventz.com/app/Data/Repositories/Invitables.php(43): Illuminate\\Support\\Collection->map(Object(Closure))
#14 /home/forge/alerj.3ventz.com/app/Data/Repositories/Invitables.php(70): App\\Data\\Repositories\\Invitables->attachInvitations('20', Array)
#15 /home/forge/alerj.3ventz.com/app/Http/Controllers/Api/Invitations.php(146): App\\Data\\Repositories\\Invitables->getInvitables('20', '{\"filter\":{\"tex...')
#16 [internal function]: App\\Http\\Controllers\\Api\\Invitations->invitables('6', '20')
#17 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#18 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('invitables', Array)
#19 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\Invitations), 'invitables')
#20 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#21 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#22 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/forge/alerj.3ventz.com/app/Http/Middleware/MustBeAppUser.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\MustBeAppUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
```

**Comment by antonioribeiro** [comment]
O fix gerou outros problemas:

```
Message
BadMethodCallException: Call to undefined method App\Data\Models\Invitation::getClientIdAttribute()

URL
https://alerj.3ventz.com/api/v1/events/6/sub-events/20/invitations?query=%7B%22filter%22%3A%7B%22text%22%3Anull%2C%22checkboxes%22%3A%7B%22filler%22%3Afalse%7D%2C%22selects%22%3A%7B%22filler%22%3Afalse%7D%7D%2C%22pagination%22%3A%7B%22total%22%3A246%2C%22p

Traceback
BadMethodCallException: Call to undefined method App\Data\Models\Invitation::getClientIdAttribute()
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php", line 50
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php", line 36, in Illuminate\Database\Eloquent\Model::throwBadMethodCallException
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php", line 1610, in Illuminate\Database\Eloquent\Model::forwardCallTo
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php", line 444, in Illuminate\Database\Eloquent\Model::__call
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php", line 456, in Illuminate\Database\Eloquent\Model::mutateAttribute
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php", line 109, in Illuminate\Database\Eloquent\Model::mutateAttributeForArray
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php", line 1076, in Illuminate\Database\Eloquent\Model::attributesToArray
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php", line 1105, in Illuminate\Database\Eloquent\Model::toArray
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php", line 1842, in Illuminate\Database\Eloquent\Model::jsonSerialize
  File "unknown", line unknown, in Illuminate\Support\Collection::Illuminate\Support\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php", line 1850, in array_map
  File "unknown", line unknown, in Illuminate\Support\Collection::jsonSerialize
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php", line 71, in json_encode
  File "/home/forge/alerj.3ventz.com/vendor/symfony/http-foundation/JsonResponse.php", line 50, in Illuminate\Http\JsonResponse::setData
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php", line 31, in Symfony\Component\HttpFoundation\JsonResponse::__construct
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line 748, in Illuminate\Http\JsonResponse::__construct
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line 722, in Illuminate\Routing\Router::toResponse
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line 682, in Illuminate\Routing\Router::prepareResponse
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 30, in Illuminate\Routing\Router::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/app/Http/Middleware/MustBeAppUser.php", line 24, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in App\Http\Middleware\MustBeAppUser::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php", line 41, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Routing\Middleware\SubstituteBindings::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php", line 43, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Auth\Middleware\Authenticate::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php", line 75, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php", line 49, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\View\Middleware\ShareErrorsFromSession::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php", line 63, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Session\Middleware\StartSession::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php", line 37, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php", line 66, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Cookie\Middleware\EncryptCookies::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 104, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line 684, in Illuminate\Pipeline\Pipeline::then
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line 659, in Illuminate\Routing\Router::runRouteWithinStack
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line 625, in Illuminate\Routing\Router::runRoute
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line 614, in Illuminate\Routing\Router::dispatchToRoute
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line 176, in Illuminate\Routing\Router::dispatch
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 30, in Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/fideloper/proxy/src/TrustProxies.php", line 57, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Fideloper\Proxy\TrustProxies::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", line 31, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", line 31, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php", line 27, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Foundation\Http\Middleware\ValidatePostSize::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php", line 62, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 163, in Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line 53, in Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line 104, in Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line 151, in Illuminate\Pipeline\Pipeline::then
  File "/home/forge/alerj.3ventz.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line 116, in Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
  File "/home/forge/alerj.3ventz.com/public/index.php", line 54, in Illuminate\Foundation\Http\Kernel::handle
```

**Comment by antonioribeiro** [comment]
Resolvido
